export interface ISalutation {
  key: string;
  value: string;
}

export const Salutation: Array<ISalutation> = [
  { key: 'Mr.', value: 'Mr.' },
  { key: 'Ms.', value: 'Ms.' },
  { key: 'Mrs.', value: 'Mrs.' },
  { key: 'Air Commdr', value: 'Air Commdr' },
  { key: 'Dr.', value: 'Dr.' },
  { key: 'Bishop', value: 'Bishop' },
  { key: 'Air Marshal', value: 'Air Marshal' },
  { key: 'Baron', value: 'Baron' },
  { key: 'Brig.', value: 'Brig.' },
  { key: 'Baroness', value: 'Baroness' },
  { key: 'Capt.', value: 'Capt.' },
  { key: 'Cardinal', value: 'Cardinal' },
  { key: 'Countess', value: 'Countess' },
  { key: 'Admiral', value: 'Admiral' },
  { key: 'Duchess', value: 'Duchess' },
  { key: 'Duke', value: 'Duke' },
  { key: 'Col.', value: 'Col.' },
  { key: 'Consul', value: 'Consul' },
  { key: 'His Excellency', value: 'His Excellency' },
  { key: 'Earl', value: 'Earl' },
  { key: 'Lady', value: 'Lady' },
  { key: 'Lord', value: 'Lord' },
  { key: 'Father', value: 'Father' },
  { key: 'Sheikh', value: 'Sheikh' },
  { key: 'Sir', value: 'Sir' },
  { key: 'Gen.', value: 'Gen.' },
  { key: 'Viscount', value: 'Viscount' },
  { key: 'Viscountess', value: 'Viscountess' },
  { key: 'Air Vice Marshal', value: 'Air Vice Marshal' },
  { key: 'Gp. Capt.', value: 'Gp. Capt.' },
  { key: 'Khun', value: 'Khun' },
  { key: 'Khunying', value: 'Khunying' },
  { key: 'King', value: 'King' },
  { key: 'Lt.', value: 'Lt.' },
  { key: 'Maestro', value: 'Maestro' },
  { key: 'Maj.', value: 'Maj.' },
  { key: 'Pastor', value: 'Pastor' },
  { key: 'Prof.', value: 'Prof.' },
  { key: 'Master', value: 'Master' },
  { key: 'Prince', value: 'Prince' },
  { key: 'Princess', value: 'Princess' },
  { key: 'Queen', value: 'Queen' },
  { key: 'Reverend', value: 'Reverend' },
  { key: 'Maharaja', value: 'Maharaja' },
  { key: 'Maharani', value: 'Maharani' },
  { key: 'Yuvraj', value: 'Yuvraj' },
  { key: 'Yuvarani', value: 'Yuvarani' },
  { key: 'Senator', value: 'Senator' },
  { key: 'Sheikha', value: 'Sheikha' },
  { key: 'Sister', value: 'Sister' },
  { key: 'Wng. Cdr', value: 'Wng. Cdr' },
  { key: 'Comdt.', value: 'Comdt.' },
  { key: 'Sqdr. Ldr.', value: 'Sqdr. Ldr.' },
  { key: 'Thanpuying', value: 'Thanpuying' },
  { key: 'Ustad', value: 'Ustad' },
  { key: 'Shri', value: 'Shri' },
  { key: 'Smt', value: 'Smt' },
  { key: 'First Officer', value: 'First Officer' },
  { key: 'Consul General', value: 'Consul General' },
  { key: 'Chief Justice', value: 'Chief Justice' },
  { key: 'Chef', value: 'Chef' },
  { key: 'Rabbi', value: 'Rabbi' },
  { key: 'Flight Lieutenant', value: 'Flight Lieutenant' },
  { key: 'Her Excellency', value: 'Her Excellency' },
  { key: 'Air Chief Marshal', value: 'Air Chief Marshal' },
  { key: 'Ambassador', value: 'Ambassador' },
  { key: 'Chancellor', value: 'Chancellor' },
  { key: 'Commander', value: 'Commander' },
  { key: 'Corporal', value: 'Corporal' },
  { key: 'Count', value: 'Count' },
  { key: 'Dato', value: 'Dato' },
  { key: 'Field Marshal', value: 'Field Marshal' },
  { key: 'Governor', value: 'Governor' },
  { key: 'Her Highness', value: 'Her Highness' },
  { key: 'Her Majesty', value: 'Her Majesty' },
  { key: 'His Highness', value: 'His Highness' },
  { key: 'His Holiness', value: 'His Holiness' },
  { key: 'His Majesty', value: 'His Majesty' },
  { key: 'Hon. Chairman', value: 'Hon. Chairman' },
  { key: 'Hon. Minister', value: 'Hon. Minister' },
  { key: 'Judge', value: 'Judge' },
  { key: 'Justice', value: 'Justice' },
  { key: 'The Honourable', value: 'The Honourable' },
  { key: 'Lt. General', value: 'Lt. General' },
  { key: 'Major General', value: 'Major General' },
  { key: 'Minister', value: 'Minister' },
  { key: 'Pandit', value: 'Pandit' },
  { key: 'Raja', value: 'Raja' },
  { key: 'Rajkumar', value: 'Rajkumar' },
  { key: 'Rajkumari', value: 'Rajkumari' },
  { key: 'Rani', value: 'Rani' },
  { key: 'Rear Admiral', value: 'Rear Admiral' },
  { key: 'Sultan', value: 'Sultan' },
  { key: 'Thakur', value: 'Thakur' },
  { key: 'Thakurani', value: 'Thakurani' },
  { key: 'Lt. Col', value: 'Lt. Col' },
  { key: 'Prof. Dr.', value: 'Prof. Dr.' },
  { key: 'Vice Admiral', value: 'Vice Admiral' },
  { key: 'Datuk', value: 'Datuk' },
  { key: 'Padma Bhushan', value: 'Padma Bhushan' },
  { key: 'Padma Shri', value: 'Padma Shri' },
  { key: 'Padma Vibhushan', value: 'Padma Vibhushan' },
];
