export const contactConfig = {
  datatable: {
    title: 'Manage Contacts',
    cols: [
      {
        field: 'email',
        header: 'Email',
        isSort: true,
        sortType: 'string',
        dynamicWidth: true,
        width: '17.5%',
      },
      {
        field: 'salutation',
        header: 'Salutation',
        isSort: true,
        sortType: 'string',
        dynamicWidth: true,
        width: '15%',
      },
      {
        field: 'firstName',
        header: 'First Name',
        isSort: true,
        sortType: 'string',
        dynamicWidth: false,
        width: '15%',
      },
      {
        field: 'lastName',
        header: 'Last Name',
        isSort: true,
        sortType: 'string',
        dynamicWidth: false,
        width: '15%',
      },
      {
        field: 'companyName',
        header: 'Company Name',
        isSort: true,
        sortType: 'string',
        dynamicWidth: false,
        width: '17.5%',
      },
      {
        field: 'mobile',
        header: 'Mobile',
        isSort: true,
        sortType: 'number',
        dynamicWidth: true,
        width: '20%',
      },
    ],
    dialogWidth: '550',
    salutationList: [
      { name: 'Mr.', value: 'Mr.' },
      { name: 'Mrs.', value: 'Mrs.' },
      { name: 'Miss', value: 'Miss' },
    ],
    fileUploadData: {
      fileSize: 3145728,
      fileType: ['csv'],
    },
  },
};
