export const contactConfig = {
  datatable: {
    title: 'Manage Contacts',
    cols: [
      {
        field: 'email',
        header: 'Email',
        sortType: 'string',
        width: '17.5%',
        isSearchDisabled: false,
        isSortDisabled: false,
      },
      {
        field: 'salutation',
        header: 'Salutation',
        sortType: 'string',
        width: '13%',
        isSearchDisabled: false,
        isSortDisabled: false,
      },
      {
        field: 'firstName',
        header: 'First Name',
        sortType: 'string',
        width: '15%',
        isSearchDisabled: false,
        isSortDisabled: false,
      },
      {
        field: 'lastName',
        header: 'Last Name',
        sortType: 'string',
        width: '15%',
        isSearchDisabled: false,
        isSortDisabled: false,
      },
      {
        field: 'companyName',
        header: 'Company Name',
        sortType: 'string',
        width: '17.5%',
        isSearchDisabled: false,
        isSortDisabled: false,
      },
      {
        field: 'mobile',
        header: 'Mobile',
        sortType: 'number',
        width: '20%',
        isSearchDisabled: false,
        isSortDisabled: false,
      },
      {
        field: '',
        header: '',
        width: '2%',
        isSearchDisabled: true,
        isSortDisabled: true,
      },
    ],
    dialogWidth: '550',
    salutationList: [
      { label: 'Mr.', value: 'Mr' },
      { label: 'Mrs.', value: 'Mrs' },
      { label: 'Miss', value: 'Miss' },
    ],
    fileUploadData: {
      fileSize: 3145728,
      fileType: ['csv'],
    },
  },
};
