export const tabFilterItems = {
  arrivals: [
    {
      label: 'Arrival',
      content: '',
      value: 'ARRIVAL',
      disabled: false,
      total: 0,
      chips: [
        {
          label: 'All',
          icon: '',
          value: 'ALL',
          total: 0,
          isSelected: true,
          type: 'default',
        },
        {
          label: 'New',
          icon: '',
          value: 'NEW',
          total: 0,
          isSelected: false,
          type: 'new',
        },
        {
          label: 'Precheckin_Pending ',
          icon: '',
          value: 'PRECHECKINPENDING',
          total: 0,
          isSelected: false,
          type: 'pending',
        },
        {
          label: 'Precheckin_Initiated ',
          icon: '',
          value: 'PRECHECKININITIATED',
          total: 0,
          isSelected: false,
          type: 'initiated',
        },
        {
          label: 'Precheckin_Complete ',
          icon: '',
          value: 'PRECHECKINCOMPLETE',
          total: 0,
          isSelected: false,
          type: 'completed',
        },
        {
          label: 'Precheckin_Failed',
          icon: '',
          value: 'PRECHECKINFAILED',
          total: 0,
          isSelected: false,
          type: 'failed',
        },
        {
          label: 'CheckIn_Pending',
          icon: '',
          value: 'CHECKINPENDING',
          total: 0,
          isSelected: false,
          type: 'pending',
        },
        {
          label: 'CheckIn_Initiated',
          icon: '',
          value: 'CHECKININITIATED',
          total: 0,
          isSelected: false,
          type: 'initiated',
        },
        {
          label: 'CheckIn_Complete',
          icon: '',
          value: 'CHECKINCOMPLETE',
          total: 0,
          isSelected: false,
          type: 'completed',
        },
        {
          label: 'CheckIn_Failed',
          icon: '',
          value: 'CHECKINFAILED',
          total: 0,
          isSelected: false,
          type: 'failed',
        },
      ],
      lastPage: 0,
    },
  ],
  inhouse: [
    {
      label: 'Inhouse',
      content: '',
      value: 'INHOUSE',
      disabled: false,
      total: 0,
      chips: [],
      lastPage: 0,
    },
  ],
  departure: [
    {
      label: 'Departure',
      content: '',
      value: 'DEPARTURE',
      disabled: false,
      total: 0,
      chips: [
        {
          label: 'All',
          icon: '',
          value: 'ALL',
          total: 0,
          isSelected: true,
          type: 'default',
        },
        {
          label: 'Checkout_Pending',
          icon: '',
          value: 'CHECKOUTPENDING',
          total: 0,
          isSelected: false,
          type: 'pending',
        },
        {
          label: 'Checkout_Initiated',
          icon: '',
          value: 'CHECKOUTINITIATED',
          total: 0,
          isSelected: false,
          type: 'initiated',
        },
        {
          label: 'CheckOut_Completed',
          icon: '',
          value: 'CHECKOUTCOMPLETED',
          total: 0,
          isSelected: false,
          type: 'completed',
        },
        {
          label: 'Checkout_Failed',
          icon: '',
          value: 'CHECKOUTFAILED',
          total: 0,
          isSelected: false,
          type: 'failed',
        },
      ],
      lastPage: 0,
    },
  ],
  reservation: [
    {
      label: 'In-house',
      content: '',
      value: 'INHOUSE',
      disabled: false,
      total: 0,
      chips: [],
      lastPage: 0,
    },
    {
      label: 'Arrival/Due-In',
      content: '',
      value: 'ARRIVAL',
      disabled: false,
      total: 0,
      chips: [
        {
          label: 'All',
          icon: '',
          value: 'ALL',
          total: 0,
          isSelected: true,

          type: 'default',
        },
        {
          label: 'New',
          icon: '',
          value: 'NEW',
          total: 0,
          isSelected: false,
          type: 'new',
        },
        {
          label: 'CheckIn_Pending',
          icon: '',
          value: 'CHECKINPENDING',
          total: 0,
          isSelected: false,
          type: 'pending',
        },
        {
          label: 'CheckIn_Initiated',
          icon: '',
          value: 'CHECKININITIATED',
          total: 0,
          isSelected: false,
          type: 'initiated',
        },
        {
          label: 'CheckIn_Complete',
          icon: '',
          value: 'CHECKINCOMPLETE',
          total: 0,
          isSelected: false,
          type: 'completed',
        },
        {
          label: 'CheckIn_Failed',
          icon: '',
          value: 'CHECKINFAILED',
          total: 0,
          isSelected: false,
          type: 'failed',
        },

        {
          label: 'Precheckin_Pending ',
          icon: '',
          value: 'PRECHECKINPENDING',
          total: 0,
          isSelected: false,
          type: 'pending',
        },
        {
          label: 'Precheckin_Initiated ',
          icon: '',
          value: 'PRECHECKININITIATED',
          total: 0,
          isSelected: false,
          type: 'initiated',
        },
        {
          label: 'Precheckin_Complete ',
          icon: '',
          value: 'PRECHECKINCOMPLETE',
          total: 0,
          isSelected: false,
          type: 'completed',
        },
        {
          label: 'Precheckin_Failed',
          icon: '',
          value: 'PRECHECKINFAILED',
          total: 0,
          isSelected: false,
          type: 'failed',
        },
      ],
      lastPage: 0,
    },
    {
      label: 'Departure/Due-out',
      content: '',
      value: 'DEPARTURE',
      disabled: false,
      total: 0,
      chips: [
        {
          label: 'All',
          icon: '',
          value: 'ALL',
          total: 0,
          isSelected: true,
          type: 'default',
        },
        {
          label: 'Checkout_Pending',
          icon: '',
          value: 'CHECKOUTPENDING',
          total: 0,
          isSelected: false,
          type: 'pending',
        },
        {
          label: 'Checkout_Initiated',
          icon: '',
          value: 'CHECKOUTINITIATED',
          total: 0,
          isSelected: false,
          type: 'initiated',
        },
        {
          label: 'CheckOut_Completed',
          icon: '',
          value: 'CHECKOUTCOMPLETED',
          total: 0,
          isSelected: false,
          type: 'completed',
        },
        {
          label: 'Checkout_Failed',
          icon: '',
          value: 'CHECKOUTFAILED',
          total: 0,
          isSelected: false,
          type: 'failed',
        },
      ],
      lastPage: 0,
    },
  ],
};
