export const assetConfig = {
  datatable: {
    title: 'Asset',
    limit: 5,
    chipValue: {
      all: 'ALL',
    },
    tabFilterItems: [
      {
        label: 'All',
        content: '',
        value: 'ALL',
        disabled: false,
        total: 0,
        chips: [
          {
            label: 'All',
            icon: '',
            value: 'ALL',
            total: 0,
            isSelected: true,
            type: 'default',
          },
          {
            label: 'Active',
            icon: '',
            value: 'ACTIVE',
            total: 0,
            isSelected: false,
            type: 'new',
          },
          {
            label: 'In-Active ',
            icon: '',
            value: 'INACTIVE',
            total: 0,
            isSelected: false,
            type: 'failed',
          },
        ],
        lastPage: 0,
      },
      {
        label: 'Image',
        content: '',
        value: 'IMAGE',
        disabled: false,
        total: 0,
        chips: [
          {
            label: 'All',
            icon: '',
            value: 'ALL',
            total: 0,
            isSelected: true,
            type: 'default',
          },
          {
            label: 'Active',
            icon: '',
            value: 'ACTIVE',
            total: 0,
            isSelected: false,
            type: 'new',
          },
          {
            label: 'In-Active ',
            icon: '',
            value: 'INACTIVE',
            total: 0,
            isSelected: false,
            type: 'failed',
          },
        ],
        lastPage: 0,
      },
      {
        label: 'Video',
        content: '',
        value: 'VIDEO',
        disabled: false,
        total: 0,
        chips: [
          {
            label: 'All',
            icon: '',
            value: 'ALL',
            total: 0,
            isSelected: true,
            type: 'default',
          },
          {
            label: 'Active',
            icon: '',
            value: 'ACTIVE',
            total: 0,
            isSelected: false,
            type: 'new',
          },
          {
            label: 'In-Active ',
            icon: '',
            value: 'INACTIVE',
            total: 0,
            isSelected: false,
            type: 'failed',
          },
        ],
        lastPage: 0,
      },
    ],
    cols: [
      {
        field: 'name',
        header: 'Name',
        sortType: 'number',
      },
      {
        field: 'description',
        header: 'Description',
        sortType: 'number',
      },
      {
        field: 'type',
        header: 'Type',
        sortType: 'string',
      },
      {
        field: 'url',
        header: 'URL',
        sortType: 'string',
      },
      {
        field: 'active',
        header: 'Active',
        isSortDisabled: true,
        sortType: 'number',

        isSearchDisabled: true,
      },
    ],
  },
  fileUploadData: {
    fileSize: 3145728,
    fileType: ['png', 'jpg', 'jpeg', 'gif', 'eps'],
  },
  type: {
    video: 'Video',
    image: 'Image',
  },
  size: {
    image: ['png', 'jpg', 'jpeg', 'gif', 'eps'],
    video: ['mp4', 'MPEG', 'MOV', 'AVI', 'MKV'],
  },
  images: {
    info: { url: 'assets/svg/info.svg', alt: 'Info' },
    download: { url: 'assets/svg/Download.svg', alt: 'Download' },
    googleDoc: { url: 'assets/svg/google-docs.svg', alt: 'Google Doc' },
    card: { url: 'assets/svg/card.svg', alt: 'Card' },
    export: { url: 'assets/svg/Export.svg', alt: 'Export' },
    csv: { url: 'assets/svg/CSV.svg', alt: 'CSV' },
    filter: { url: 'assets/svg/Filter-Icon.svg', alt: 'Filter' },
    copy: { url: 'assets/svg/copy.svg', alt: 'copy' },
  },
};
