export const dataList = [
  {
    id: '1',
    nameTitle: 'Mr.',
    firstName: 'John',
    lastName: 'Doe',
    contactDetails: {
      cc: '+1',
      contactNumber: '1234567890',
      emailId: 'john.doe@example.com',
    },
    nationality: 'US',
    age: 30,
    address: {
      addressLine1: '123 Main St',
      city: 'New York',
      state: 'NY',
      countryCode: 'US',
      postalCode: '12345',
    },
    salesPersonName: 'Jane Smith',
    salesPersonPhone: '9876543210',
    iataNumber: '12345678',
    priceModifier: '10%',
    pricaModifierType: 'Percentage',
    priceModifierValue: '10',
    companyName: 'ABC Company',
    companyCode: 1234,
    action: true,
    companyId: 'C1',
  },
  {
    id: '1',
    nameTitle: 'Mr.',
    firstName: 'John',
    lastName: 'Doe',
    contactDetails: {
      cc: '+1',
      contactNumber: '1234567890',
      emailId: 'john.doe@example.com',
    },
    nationality: 'US',
    age: 30,
    address: {
      addressLine1: '123 Main St',
      city: 'New York',
      state: 'NY',
      countryCode: 'US',
      postalCode: '12345',
    },
    salesPersonName: 'Jane Smith',
    salesPersonPhone: '9876543210',
    iataNumber: '12345678',
    priceModifier: '10%',
    pricaModifierType: 'Percentage',
    priceModifierValue: '10',
    companyName: 'ABC Company',
    companyCode: 1234,
    action: true,
    companyId: 'C1',
  },
];
