export const authConstants = {
  linkUrl: {
    termsAndCondition: 'https://www.botshot.in/terms-of-uses/',
    aboutUs: 'https://www.botshot.in/about-us/',
    privacyPolicy: 'https://www.botshot.in/privacy-policy/',
  },
  imgUrl: {
    bell: 'assets/svg/bell.svg',
    hotel: 'assets/svg/hotel.svg',
    luggage: 'assets/svg/luggage.svg',
    metroHotel: 'assets/svg/metro-hotel.svg',
    liveDashboard: 'assets/svg/dashboard-white.svg',
    filter: 'assets/svg/Filter.svg',
    analytics: 'assets/svg/Analytics.svg',
    liveRequest: 'assets/svg/live-help.svg',
    search: 'assets/svg/search.svg',
    botshotLogo: 'assets/images/botshotlogo.png',
  },
  managingOptions: [
    { id: 1, label: 'Live Dashboard', url: 'assets/svg/dashboard-white.svg' },
    { id: 2, label: 'Filters as per Journeys', url: 'assets/svg/Filter.svg' },
    { id: 3, label: 'Analytics', url: 'assets/svg/Analytics.svg' },
    {
      id: 4,
      label: 'Live Request Handling',
      url: 'assets/svg/live-help.svg',
    },
    { id: 5, label: 'Universal Search', url: 'assets/svg/search.svg' },
  ],
  alt: {
    bell: 'bell',
    hotel: 'hotel',
    luggage: 'luggage',
    metroHotel: 'metro-hotel',
    liveDashboard: 'dashboard',
    filter: 'Filter',
    analytics: 'Analytics',
    liveRequest: 'live-help',
    search: 'search',
    botshotLogo: 'botshotlogo',
  },
  passwordMinLength: 6,
  passwordMaxLength: 10,
};
