export type ReservationType =
  | 'CHECKINPENDING'
  | 'CHECKININITIATED'
  | 'CHECKINCOMPLETE'
  | 'CHECKINFAILED'
  | 'PRECHECKINPENDING'
  | 'PRECHECKININITIATED'
  | 'PRECHECKINFAILED'
  | 'PRECHECKINCOMPLETE'
  | 'NEW'
  | 'CHECKOUTCOMPLETED'
  | 'CHECKOUTFAILED'
  | 'CHECKOUTINITIATED'
  | 'CHECKOUTPENDING';

export type ReservationTab = 'INHOUSE' | 'ARRIVAL' | 'DEPARTURE';
