export type ReservationType =
  | 'CHECKINPENDING'
  | 'CHECKININITIATED'
  | 'CHECKINCOMPLETE'
  | 'CHECKINFAILED'
  | 'PRECHECKINPENDING'
  | 'PRECHECKININITIATED'
  | 'PRECHECKINFAILED'
  | 'PRECHECKINCOMPLETE'
  | 'NEW';

export type ReservationTab = 'INHOUSE' | 'ARRIVAL' | 'DEPARTURE';
