const StepsArray = [
  'STAYDETAILS',
  'GUESTDETAILS',
  'DOCUMENTS',
  'PAYMENT',
  // 'HEALTHDECLARATION',
  'SUMMARY',
];

export const stepsIndexData = {
  STAYDETAILS: 0,
  GUESTDETAILS: 1,
  DOCUMENTS: 2,
  PAYMENT: 3,
  HEALTHDECLARATION: 4,
  SUMMARY: 4,
};
